---
title: "Capstone Project Statistical Analysis"
author: "Anna Vaughan"
date: "January 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```  

Now let's write down our findings in a short document. This document will become part of your milestone report, and eventually your final project report.

    Summarize the most interesting or important findings from your analysis in a short (2-3 page) document. You may use any format of your choice (R Markdown, Google Docs, Word etc)
    
  
## Capstone Project Statistical Analysis
  
  
### Revised problem that my Capstone project will solve
The overall aim is to understand where MMU's applications are stronger than UoS's (in terms of application numbers, subject balance and applicant regional origin), to help UoS academics and marketing teams understand where recruitment opportunities may be being missed, so that they can focus effort and resources on those opportunities.
-	How do overall UCAS application numbers to the University of Salford (UoS) compare with application numbers to Manchester Metropolitan University (MMU)? Who receives more applications?
- How did overall UCAS application numbers to each university change over time from 2006 to 2016? Did one grow ahead of the other?
- How does the spread of subject groups applied for at MMU and Salford compare?
-	How does the spread of subjects applied for UK-wide compare to the spread at MMU and UoS?
-	How does the spread of applicant domiciles at MMU compare with that at UoS?


#### Overall UCAS application numbers to UoS vs MMU
- What were application numbers at MMU and Salford, across the period 2006 to 2016?
Reshaping the data to MMU_Salf_App_Numbers_5 showed the data as one year per column just for the two institutions being compared: application numbers to MMU look to be consistently larger than those for Salford for each year, with application numbers to MMU mostly more than double those to Salford, though in some years the difference was larger than others.

Reshaping the data to MMU_Salf_App_Numbers_6 showed the data as one institution per column just for the two institutions being compared, allowing me to sum applications across the 11 years: total application numbers to MMU were 522,190 (70.5% of the two institutions' combined total), while those to Salford were 217,580 (29.5% of the total). 

#### Trends in UCAS application numbers to UoS vs MMU over time
-	How have application number changed over time at MMU and UoS?
UoS saw a consistent increase in applications 2006 to 2011, then a sharp fall in 2012 followed by a gradual increase to 2016. UoS received its smallest number of applications in 2006 (16,325) and its largest in 2016 (23,660).

MMU's application numbers followed a more complex pattern: in addition to the pattern seen in UoS's numbers, MMU also saw a dip in applications in 2008, and saw fewer applications in 2015 and 2016 than it did in 2014. 

Plotting the percentage share of the total applications to both institutions that each received shows that UoS's percentage share of the applications to both institutions fluctuated between 27% and 32% across the period 2006-2016, with UoS's share increasing fairly steadily in recent years (between 2013 and 2016).

(There seems to be far more variability in MMU’s applications than Salford’s year-on-year, but it would be good to look at the variance and standard deviation to check this).

#### How does the spread of subject groups applied for at MMU and Salford compare?

#### How does the spread of subjects applied for UK-wide compare to the spread at MMU and UoS?

#### How does the spread of applicant domiciles at MMU compare with that at UoS?


Can I make a bar plot or histogram?
Creating a histogram comparing the percentage of applications to each institution showed a relatively stable balance of applications, that nonetheless fluctuated slightly year-on-year. 
Can I compare two related quantitites?
-	How does the spread of subject groups applied for at MMU and Salford compare?
-	How does the spread of subjects applied for UK-wide compare to the spread at MMU and Salford?
-	How has that changed over time?
-	How does the spread of applicant domiciles at MMU compare with that at Salford?  
-	How has that changed over time?
Can I make a scatterplot?
Creating a scatterplot comparing the percentages of applications to different subject areas for MMU, UoS and UCAS overall 



Understand the profile of students who studied each UCAS subject area in the UK for the academic year 2016/17, in terms of their region of origin and the university they chose to study at.  
  
  
